Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Models/Abono.cs
namespace Practica3PrograAW_API.Models
{
    public class Abono
    {
        public long IdCompra {  get; set; }
        public long IdAbono { get; set; }
        public double Monto { get; set; }
        public DateTime Fecha { get; set; }

    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Models/ErrorViewModel.cs
namespace Practica3PrograAvW_WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Models/Producto.cs
namespace Practica3PrograAvW_WEB.Models
{
    public class Producto
    {
        public long IdCompra { get; set; }
        public double Precio { get; set; }
        public double Saldo { get; set; }
        public string Descripcion { get; set; } = string.Empty;
        public string Estado { get; set; } = string.Empty;
    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Models/Respuesta.cs
namespace Practica3PrograAvW_WEB.Models
{
    public class Respuesta
    {
        public int Codigo { get; set; }
        public string Mensaje { get; set; } = string.Empty;
        public object? Contenido { get; set; }
    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practica3PrograAvW_WEB.Models;
using System.Diagnostics;

namespace Practica3PrograAvW_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Controllers/PagoController.cs
using Microsoft.AspNetCore.Mvc;
using Practica3PrograAvW_WEB.Models;
using System.Text.Json;

namespace Practica3PrograAvW_WEB.Controllers
{
    public class PagoController : Controller
    {
        private readonly IHttpClientFactory _http;
        private readonly IConfiguration _conf;

        public PagoController(IHttpClientFactory http, IConfiguration conf)
        {
            _http = http;
            _conf = conf;
        }

        [HttpGet]
        public IActionResult RealizarPago()
        {
            using(var client = _http.CreateClient())
            {
                var url = _conf.GetSection("Variables:UrlApi").Value + "Producto/ConsultarProductosPendientes";
                var response = client.GetAsync(url).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                if (result != null && result.Codigo == 0)
                {
                    var productosPendientes = JsonSerializer.Deserialize<List<Producto>>((JsonElement)result.Contenido!);
                    // Retornamos a la vista RealizarPago con los productos obtenidos
                    return View(productosPendientes);
                }
                else
                {
                    // Si no hay productos, se retorna una lista vacía
                    return View(new List<Producto>());
                }
            }
        }

    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Practica3PrograAvW_WEB.Models;
using System.Text.Json;

namespace Practica3PrograAvW_WEB.Controllers
{
    public class ProductoController : Controller
    {

        private readonly IHttpClientFactory _http;
        private readonly IConfiguration _conf;

        public ProductoController(IHttpClientFactory http, IConfiguration conf)
        {
            _http = http;
            _conf = conf;
        }

        [HttpGet]
        public IActionResult ConsultarProductos()
        {
            using(var client = _http.CreateClient())
            {
                var url = _conf.GetSection("Variables:UrlApi").Value + "Producto/ConsultarProductos";

                var response = client.GetAsync(url).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;
                
                if(result != null && result.Codigo == 0)
                {
                    var datosContenido = JsonSerializer.Deserialize<List<Producto>>((JsonElement)result.Contenido!);
                    var productosOrdenados = datosContenido.OrderBy(p => p.Estado == "Pendiente" ? 0:1)
                        .ThenBy(p=>p.Estado).ToList();
                    
                    return View(productosOrdenados);
                }

                return View(new List<Producto>());
            
            }
        }


        [HttpGet]
        public IActionResult ConsultarProductosPendientes()
        {
            using (var client = _http.CreateClient())
            {
                var url = _conf.GetSection("Variables:UrlApi").Value + "Producto/ConsultarProductosPendientes";

                var response = client.GetAsync(url).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                if (result != null && result.Codigo == 0)
                {
                    var datosContenido = JsonSerializer.Deserialize<List<Producto>>((JsonElement)result.Contenido!);
                    return View(datosContenido);
                }

                return View(new List<Producto>());

            }
        }

    }
}

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Views/Pago/RealizarPago.cshtml
@model List<Producto>

<form method="post" action="@Url.Action("", "")">
    <div class="form-group">
        <label for="producto">Selecciona el producto pendiente:</label>
        <select id="producto" name="productoId" class="form-control">
            <option value="">-- Selecciona un producto --</option>
            @foreach (var producto in Model)
            {
                <option value="@producto.IdCompra">@producto.Descripcion</option>
            }
        </select>
    </div>

    <div >
        <label for="saldoAnterior">Saldo Anterior:</label>
        <input type="text" class="form-control" id="saldoAnterior" name="saldoAnterior" />
    </div>

    <div class="form-group">
        <label for="abono">Abono:</label>
        <input type="text" class="form-control" id="abono" name="abono" />
    </div>

    <button type="submit" class="btn btn-primary">Abonar</button>
</form>

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Views/Producto/ConsultarProductos.cshtml
@model List<Producto>


<div class="card">
    <div class="card-body">
        <h5 class="card-title">Lista de Vehiculos</h5>

        <div class="table-responsive">
            <table class="table text-nowrap align-middle mb-0">
                <thead>
                    <tr class="border-2 border-bottom border-primary border-0">
                        <th>Codigo Compra</th>
                        <th>Descripcion</th>
                        <th>Precio</th>
                        <th>Saldo</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    @foreach (var producto in Model)
                    {
                        <tr>
                            <td>@producto.IdCompra</td>
                            <td>@producto.Descripcion</td>
                            <td>@producto.Precio</td>
                            <td>@producto.Saldo</td>
                            <td>@producto.Estado</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Practica3PrograAvW_WEB/Practica3PrograAvW_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Practica3</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon" href="~/img/favicon.ico" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/plugins.min.css" />
    <link rel="stylesheet" href="~/css/kaiadmin.min.css" />
    <link rel="stylesheet" href="~/css/demo.css" />

</head>
<body>
    <div class="wrapper">

        <div class="sidebar" data-background-color="dark">

            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <ul class="nav nav-secondary">

                        <li class="nav-section">
                            <span class="sidebar-mini-icon">
                                <i class="fa fa-ellipsis-h"></i>
                            </span>
                            <h4 class="text-section">Secciones</h4>
                        </li>
                        <li class="nav-item">
                            <a class="sidebar-link" href="@Url.Action("ConsultarProductos", "Producto")">

                                <span>
                                    <iconify-icon icon="solar:home-smile-bold-duotone" class="fs-6"></iconify-icon>
                                </span>
                                <span class="hide-menu">Consultar Producto</span>

                            </a>

                        </li>
                        <li class="nav-item">
                            <a class="sidebar-link" href="@Url.Action("RealizarPago", "Pago")">

                                <span>
                                    <iconify-icon icon="solar:home-smile-bold-duotone" class="fs-6"></iconify-icon>
                                </span>
                                <span class="hide-menu">Realizar Pago</span>

                            </a>

                        </li>
                      
                    </ul>
                </div>
            </div>
        </div>

        <div class="main-panel">
            <div class="main-header">
                <div class="main-header-logo">

                    <div class="logo-header" data-background-color="dark">
                        <a href="index.html" class="logo">
                            <img src="~/img/logo_light.svg"
                                 alt="navbar brand"
                                 class="navbar-brand"
                                 height="20" />
                        </a>
                        <div class="nav-toggle">
                            <button class="btn btn-toggle toggle-sidebar">
                                <i class="gg-menu-right"></i>
                            </button>
                            <button class="btn btn-toggle sidenav-toggler">
                                <i class="gg-menu-left"></i>
                            </button>
                        </div>
                        <button class="topbar-toggler more">
                            <i class="gg-more-vertical-alt"></i>
                        </button>
                    </div>

                </div>

                <nav

          </nav>

            </div>

            <div class="container">
                @RenderBody();

            </div>

        </div>

    </div>

    <script src="~/js/jquery-3.7.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/popper.min.js"></script>


</body>
</html>